name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  deploy:
    name: Upload Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.36", "3.38", "40.0"]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: GitHub Container Registry Login
      run: |
        # This requires root due to https://github.com/containers/podman/issues/9936
        echo "${{ secrets.CR_PAT }}" | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and Push
      run: |
        IMAGE=ghcr.io/${{ github.actor }}/gnome-shell

        # Change all uppercase to lowercase.
        IMAGE=$(echo $IMAGE | tr '[A-Z]' '[a-z]')

        # Build the image. This requires root due to https://github.com/containers/podman/issues/9936
        sudo podman build -t $IMAGE:${{ matrix.version }} -t $IMAGE:latest -f Dockerfile.${{ matrix.version }} .

        # Push the version tag. This requires root due to https://github.com/containers/podman/issues/9936
        sudo podman push $IMAGE:${{ matrix.version }}
        
        # Push the latest tag for GNOME Shell 40.0
        if [ "${{ matrix.version }}" = "40.0" ]; then
          sudo podman push $IMAGE:latest
        fi
