on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - "**"

jobs:
  build:
    name: Deploy Rawhide Container
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-rawhide
      - uses: docker/build-push-action@v2
        with:
          build-args: fedora_version=rawhide
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
