on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - "**"

jobs:
  build:
    name: Deploy Rawhide Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-rawhide

      - uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            fedora_version=rawhide
          pull: true
          push: true
          cache-from: |
            ghcr.io/${{ github.repository }}-rawhide:main
            ${{ steps.docker_meta.outputs.tags }}
          cache-to: type=inline
